//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODOTTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODOTTO()
        {
            this.FATTURAACQUISTO = new HashSet<FATTURAACQUISTO>();
            this.FATTURAVENDITA = new HashSet<FATTURAVENDITA>();
        }
    
        public string IDPRODOTTO { get; set; }
        public string NOME { get; set; }
        public string DESCRIZIONE { get; set; }
        public double PREZZO { get; set; }
        public int QUANTITA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATTURAACQUISTO> FATTURAACQUISTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATTURAVENDITA> FATTURAVENDITA { get; set; }
    }
}
