//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTENTE()
        {
            this.FATTURAACQUISTO = new HashSet<FATTURAACQUISTO>();
            this.FATTURAVENDITA = new HashSet<FATTURAVENDITA>();
        }
    
        public string IDUTENTE { get; set; }
        public string NOME { get; set; }
        public string COGNOME { get; set; }
        public string PASSWORD { get; set; }
        public int ISADMIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATTURAACQUISTO> FATTURAACQUISTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATTURAVENDITA> FATTURAVENDITA { get; set; }
    }
}
