//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneMagazzino.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtenteClass", Namespace="http://schemas.datacontract.org/2004/07/WCFServer")]
    [System.SerializableAttribute()]
    public partial class UtenteClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdutenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idutente {
            get {
                return this.IdutenteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdutenteField, value) != true)) {
                    this.IdutenteField = value;
                    this.RaisePropertyChanged("Idutente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FornitoreClass", Namespace="http://schemas.datacontract.org/2004/07/WCFServer")]
    [System.SerializableAttribute()]
    public partial class FornitoreClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdfornitoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitaivaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idfornitore {
            get {
                return this.IdfornitoreField;
            }
            set {
                if ((object.ReferenceEquals(this.IdfornitoreField, value) != true)) {
                    this.IdfornitoreField = value;
                    this.RaisePropertyChanged("Idfornitore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partitaiva {
            get {
                return this.PartitaivaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitaivaField, value) != true)) {
                    this.PartitaivaField = value;
                    this.RaisePropertyChanged("Partitaiva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteClass", Namespace="http://schemas.datacontract.org/2004/07/WCFServer")]
    [System.SerializableAttribute()]
    public partial class ClienteClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodicefiscaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitaivaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codicefiscale {
            get {
                return this.CodicefiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodicefiscaleField, value) != true)) {
                    this.CodicefiscaleField = value;
                    this.RaisePropertyChanged("Codicefiscale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcliente {
            get {
                return this.IdclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdclienteField, value) != true)) {
                    this.IdclienteField = value;
                    this.RaisePropertyChanged("Idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partitaiva {
            get {
                return this.PartitaivaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitaivaField, value) != true)) {
                    this.PartitaivaField = value;
                    this.RaisePropertyChanged("Partitaiva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdottoClass", Namespace="http://schemas.datacontract.org/2004/07/WCFServer")]
    [System.SerializableAttribute()]
    public partial class ProdottoClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdprodottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InesaurimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrezzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idprodotto {
            get {
                return this.IdprodottoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdprodottoField, value) != true)) {
                    this.IdprodottoField = value;
                    this.RaisePropertyChanged("Idprodotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inesaurimento {
            get {
                return this.InesaurimentoField;
            }
            set {
                if ((this.InesaurimentoField.Equals(value) != true)) {
                    this.InesaurimentoField = value;
                    this.RaisePropertyChanged("Inesaurimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prezzo {
            get {
                return this.PrezzoField;
            }
            set {
                if ((this.PrezzoField.Equals(value) != true)) {
                    this.PrezzoField = value;
                    this.RaisePropertyChanged("Prezzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FatturaAcquistoClass", Namespace="http://schemas.datacontract.org/2004/07/WCFServer")]
    [System.SerializableAttribute()]
    public partial class FatturaAcquistoClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodFornitoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodProdottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodUtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAcquistoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NfatturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrezzoAcquistoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodFornitore {
            get {
                return this.CodFornitoreField;
            }
            set {
                if ((object.ReferenceEquals(this.CodFornitoreField, value) != true)) {
                    this.CodFornitoreField = value;
                    this.RaisePropertyChanged("CodFornitore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProdotto {
            get {
                return this.CodProdottoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodProdottoField, value) != true)) {
                    this.CodProdottoField = value;
                    this.RaisePropertyChanged("CodProdotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUtente {
            get {
                return this.CodUtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodUtenteField, value) != true)) {
                    this.CodUtenteField = value;
                    this.RaisePropertyChanged("CodUtente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAcquisto {
            get {
                return this.DataAcquistoField;
            }
            set {
                if ((this.DataAcquistoField.Equals(value) != true)) {
                    this.DataAcquistoField = value;
                    this.RaisePropertyChanged("DataAcquisto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nfattura {
            get {
                return this.NfatturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NfatturaField, value) != true)) {
                    this.NfatturaField = value;
                    this.RaisePropertyChanged("Nfattura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrezzoAcquisto {
            get {
                return this.PrezzoAcquistoField;
            }
            set {
                if ((this.PrezzoAcquistoField.Equals(value) != true)) {
                    this.PrezzoAcquistoField = value;
                    this.RaisePropertyChanged("PrezzoAcquisto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FatturaVenditaClass", Namespace="http://schemas.datacontract.org/2004/07/WCFServer")]
    [System.SerializableAttribute()]
    public partial class FatturaVenditaClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodProdottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodUtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataVenditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NfatturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrezzoVenditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodClienteField, value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProdotto {
            get {
                return this.CodProdottoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodProdottoField, value) != true)) {
                    this.CodProdottoField = value;
                    this.RaisePropertyChanged("CodProdotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUtente {
            get {
                return this.CodUtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodUtenteField, value) != true)) {
                    this.CodUtenteField = value;
                    this.RaisePropertyChanged("CodUtente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataVendita {
            get {
                return this.DataVenditaField;
            }
            set {
                if ((this.DataVenditaField.Equals(value) != true)) {
                    this.DataVenditaField = value;
                    this.RaisePropertyChanged("DataVendita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nfattura {
            get {
                return this.NfatturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NfatturaField, value) != true)) {
                    this.NfatturaField = value;
                    this.RaisePropertyChanged("Nfattura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pagamento {
            get {
                return this.PagamentoField;
            }
            set {
                if ((this.PagamentoField.Equals(value) != true)) {
                    this.PagamentoField = value;
                    this.RaisePropertyChanged("Pagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrezzoVendita {
            get {
                return this.PrezzoVenditaField;
            }
            set {
                if ((this.PrezzoVenditaField.Equals(value) != true)) {
                    this.PrezzoVenditaField = value;
                    this.RaisePropertyChanged("PrezzoVendita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/DoWork", ReplyAction="http://tempuri.org/IServerService/DoWorkResponse")]
        bool DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/DoWork", ReplyAction="http://tempuri.org/IServerService/DoWorkResponse")]
        System.Threading.Tasks.Task<bool> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/RegisterUtente", ReplyAction="http://tempuri.org/IServerService/RegisterUtenteResponse")]
        bool RegisterUtente(string Nome, string Cognome, string Password, int IsAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/RegisterUtente", ReplyAction="http://tempuri.org/IServerService/RegisterUtenteResponse")]
        System.Threading.Tasks.Task<bool> RegisterUtenteAsync(string Nome, string Cognome, string Password, int IsAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/LoginUtente", ReplyAction="http://tempuri.org/IServerService/LoginUtenteResponse")]
        int LoginUtente(string IDutente, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/LoginUtente", ReplyAction="http://tempuri.org/IServerService/LoginUtenteResponse")]
        System.Threading.Tasks.Task<int> LoginUtenteAsync(string IDutente, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetUtente", ReplyAction="http://tempuri.org/IServerService/GetUtenteResponse")]
        GestioneMagazzino.ServiceReference1.UtenteClass GetUtente(string IDutente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetUtente", ReplyAction="http://tempuri.org/IServerService/GetUtenteResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.UtenteClass> GetUtenteAsync(string IDutente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetUtenteisAdmin", ReplyAction="http://tempuri.org/IServerService/SetUtenteisAdminResponse")]
        bool SetUtenteisAdmin(string IDutente, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetUtenteisAdmin", ReplyAction="http://tempuri.org/IServerService/SetUtenteisAdminResponse")]
        System.Threading.Tasks.Task<bool> SetUtenteisAdminAsync(string IDutente, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/UtentiList", ReplyAction="http://tempuri.org/IServerService/UtentiListResponse")]
        GestioneMagazzino.ServiceReference1.UtenteClass[] UtentiList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/UtentiList", ReplyAction="http://tempuri.org/IServerService/UtentiListResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.UtenteClass[]> UtentiListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/FornitoriList", ReplyAction="http://tempuri.org/IServerService/FornitoriListResponse")]
        GestioneMagazzino.ServiceReference1.FornitoreClass[] FornitoriList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/FornitoriList", ReplyAction="http://tempuri.org/IServerService/FornitoriListResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.FornitoreClass[]> FornitoriListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertFornitore", ReplyAction="http://tempuri.org/IServerService/InsertFornitoreResponse")]
        bool InsertFornitore(string Nome, string PartitaIVA, string Email, string Indirizzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertFornitore", ReplyAction="http://tempuri.org/IServerService/InsertFornitoreResponse")]
        System.Threading.Tasks.Task<bool> InsertFornitoreAsync(string Nome, string PartitaIVA, string Email, string Indirizzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/ClientiList", ReplyAction="http://tempuri.org/IServerService/ClientiListResponse")]
        GestioneMagazzino.ServiceReference1.ClienteClass[] ClientiList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/ClientiList", ReplyAction="http://tempuri.org/IServerService/ClientiListResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.ClienteClass[]> ClientiListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertCliente", ReplyAction="http://tempuri.org/IServerService/InsertClienteResponse")]
        bool InsertCliente(string Nome, string PartitaIVA, string Codicefiscale, string Indirizzo, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertCliente", ReplyAction="http://tempuri.org/IServerService/InsertClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertClienteAsync(string Nome, string PartitaIVA, string Codicefiscale, string Indirizzo, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/ProdottiList", ReplyAction="http://tempuri.org/IServerService/ProdottiListResponse")]
        GestioneMagazzino.ServiceReference1.ProdottoClass[] ProdottiList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/ProdottiList", ReplyAction="http://tempuri.org/IServerService/ProdottiListResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.ProdottoClass[]> ProdottiListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertProdotto", ReplyAction="http://tempuri.org/IServerService/InsertProdottoResponse")]
        bool InsertProdotto(string IDprodotto, string Nome, string Descrizione, double Prezzo, int Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertProdotto", ReplyAction="http://tempuri.org/IServerService/InsertProdottoResponse")]
        System.Threading.Tasks.Task<bool> InsertProdottoAsync(string IDprodotto, string Nome, string Descrizione, double Prezzo, int Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Addquantitaprodotto", ReplyAction="http://tempuri.org/IServerService/AddquantitaprodottoResponse")]
        bool Addquantitaprodotto(string IDprodotto, int Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Addquantitaprodotto", ReplyAction="http://tempuri.org/IServerService/AddquantitaprodottoResponse")]
        System.Threading.Tasks.Task<bool> AddquantitaprodottoAsync(string IDprodotto, int Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Minusquantitaprodotto", ReplyAction="http://tempuri.org/IServerService/MinusquantitaprodottoResponse")]
        bool Minusquantitaprodotto(string IDprodotto, int Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Minusquantitaprodotto", ReplyAction="http://tempuri.org/IServerService/MinusquantitaprodottoResponse")]
        System.Threading.Tasks.Task<bool> MinusquantitaprodottoAsync(string IDprodotto, int Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Disprodotto", ReplyAction="http://tempuri.org/IServerService/DisprodottoResponse")]
        GestioneMagazzino.ServiceReference1.ProdottoClass Disprodotto(string Idprodotto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Disprodotto", ReplyAction="http://tempuri.org/IServerService/DisprodottoResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.ProdottoClass> DisprodottoAsync(string Idprodotto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AlterNomeProdotto", ReplyAction="http://tempuri.org/IServerService/AlterNomeProdottoResponse")]
        bool AlterNomeProdotto(string IDprodotto, string Nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AlterNomeProdotto", ReplyAction="http://tempuri.org/IServerService/AlterNomeProdottoResponse")]
        System.Threading.Tasks.Task<bool> AlterNomeProdottoAsync(string IDprodotto, string Nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AlterPrezzoProdotto", ReplyAction="http://tempuri.org/IServerService/AlterPrezzoProdottoResponse")]
        bool AlterPrezzoProdotto(string IDprodotto, double Prezzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AlterPrezzoProdotto", ReplyAction="http://tempuri.org/IServerService/AlterPrezzoProdottoResponse")]
        System.Threading.Tasks.Task<bool> AlterPrezzoProdottoAsync(string IDprodotto, double Prezzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/FattureAcquistoList", ReplyAction="http://tempuri.org/IServerService/FattureAcquistoListResponse")]
        GestioneMagazzino.ServiceReference1.FatturaAcquistoClass[] FattureAcquistoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/FattureAcquistoList", ReplyAction="http://tempuri.org/IServerService/FattureAcquistoListResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.FatturaAcquistoClass[]> FattureAcquistoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/FattureVenditaList", ReplyAction="http://tempuri.org/IServerService/FattureVenditaListResponse")]
        GestioneMagazzino.ServiceReference1.FatturaVenditaClass[] FattureVenditaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/FattureVenditaList", ReplyAction="http://tempuri.org/IServerService/FattureVenditaListResponse")]
        System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.FatturaVenditaClass[]> FattureVenditaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AlterPagatoFattura", ReplyAction="http://tempuri.org/IServerService/AlterPagatoFatturaResponse")]
        bool AlterPagatoFattura(string Nfattura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AlterPagatoFattura", ReplyAction="http://tempuri.org/IServerService/AlterPagatoFatturaResponse")]
        System.Threading.Tasks.Task<bool> AlterPagatoFatturaAsync(string Nfattura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertFatturaVendita", ReplyAction="http://tempuri.org/IServerService/InsertFatturaVenditaResponse")]
        bool InsertFatturaVendita(string Nfattura, string CodUtente, string CodCliente, string CodProdotto, int Quantita, bool Pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertFatturaVendita", ReplyAction="http://tempuri.org/IServerService/InsertFatturaVenditaResponse")]
        System.Threading.Tasks.Task<bool> InsertFatturaVenditaAsync(string Nfattura, string CodUtente, string CodCliente, string CodProdotto, int Quantita, bool Pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertFatturaAcquisto", ReplyAction="http://tempuri.org/IServerService/InsertFatturaAcquistoResponse")]
        bool InsertFatturaAcquisto(string Nfattura, string CodUtente, string CodFornitore, string CodProdotto, int Quantita, double PrezzoAcquisto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/InsertFatturaAcquisto", ReplyAction="http://tempuri.org/IServerService/InsertFatturaAcquistoResponse")]
        System.Threading.Tasks.Task<bool> InsertFatturaAcquistoAsync(string Nfattura, string CodUtente, string CodFornitore, string CodProdotto, int Quantita, double PrezzoAcquisto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/NFatturaVendita", ReplyAction="http://tempuri.org/IServerService/NFatturaVenditaResponse")]
        string NFatturaVendita();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/NFatturaVendita", ReplyAction="http://tempuri.org/IServerService/NFatturaVenditaResponse")]
        System.Threading.Tasks.Task<string> NFatturaVenditaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : GestioneMagazzino.ServiceReference1.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<GestioneMagazzino.ServiceReference1.IServerService>, GestioneMagazzino.ServiceReference1.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<bool> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool RegisterUtente(string Nome, string Cognome, string Password, int IsAdmin) {
            return base.Channel.RegisterUtente(Nome, Cognome, Password, IsAdmin);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUtenteAsync(string Nome, string Cognome, string Password, int IsAdmin) {
            return base.Channel.RegisterUtenteAsync(Nome, Cognome, Password, IsAdmin);
        }
        
        public int LoginUtente(string IDutente, string Password) {
            return base.Channel.LoginUtente(IDutente, Password);
        }
        
        public System.Threading.Tasks.Task<int> LoginUtenteAsync(string IDutente, string Password) {
            return base.Channel.LoginUtenteAsync(IDutente, Password);
        }
        
        public GestioneMagazzino.ServiceReference1.UtenteClass GetUtente(string IDutente) {
            return base.Channel.GetUtente(IDutente);
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.UtenteClass> GetUtenteAsync(string IDutente) {
            return base.Channel.GetUtenteAsync(IDutente);
        }
        
        public bool SetUtenteisAdmin(string IDutente, int status) {
            return base.Channel.SetUtenteisAdmin(IDutente, status);
        }
        
        public System.Threading.Tasks.Task<bool> SetUtenteisAdminAsync(string IDutente, int status) {
            return base.Channel.SetUtenteisAdminAsync(IDutente, status);
        }
        
        public GestioneMagazzino.ServiceReference1.UtenteClass[] UtentiList() {
            return base.Channel.UtentiList();
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.UtenteClass[]> UtentiListAsync() {
            return base.Channel.UtentiListAsync();
        }
        
        public GestioneMagazzino.ServiceReference1.FornitoreClass[] FornitoriList() {
            return base.Channel.FornitoriList();
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.FornitoreClass[]> FornitoriListAsync() {
            return base.Channel.FornitoriListAsync();
        }
        
        public bool InsertFornitore(string Nome, string PartitaIVA, string Email, string Indirizzo) {
            return base.Channel.InsertFornitore(Nome, PartitaIVA, Email, Indirizzo);
        }
        
        public System.Threading.Tasks.Task<bool> InsertFornitoreAsync(string Nome, string PartitaIVA, string Email, string Indirizzo) {
            return base.Channel.InsertFornitoreAsync(Nome, PartitaIVA, Email, Indirizzo);
        }
        
        public GestioneMagazzino.ServiceReference1.ClienteClass[] ClientiList() {
            return base.Channel.ClientiList();
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.ClienteClass[]> ClientiListAsync() {
            return base.Channel.ClientiListAsync();
        }
        
        public bool InsertCliente(string Nome, string PartitaIVA, string Codicefiscale, string Indirizzo, string Email) {
            return base.Channel.InsertCliente(Nome, PartitaIVA, Codicefiscale, Indirizzo, Email);
        }
        
        public System.Threading.Tasks.Task<bool> InsertClienteAsync(string Nome, string PartitaIVA, string Codicefiscale, string Indirizzo, string Email) {
            return base.Channel.InsertClienteAsync(Nome, PartitaIVA, Codicefiscale, Indirizzo, Email);
        }
        
        public GestioneMagazzino.ServiceReference1.ProdottoClass[] ProdottiList() {
            return base.Channel.ProdottiList();
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.ProdottoClass[]> ProdottiListAsync() {
            return base.Channel.ProdottiListAsync();
        }
        
        public bool InsertProdotto(string IDprodotto, string Nome, string Descrizione, double Prezzo, int Quantita) {
            return base.Channel.InsertProdotto(IDprodotto, Nome, Descrizione, Prezzo, Quantita);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProdottoAsync(string IDprodotto, string Nome, string Descrizione, double Prezzo, int Quantita) {
            return base.Channel.InsertProdottoAsync(IDprodotto, Nome, Descrizione, Prezzo, Quantita);
        }
        
        public bool Addquantitaprodotto(string IDprodotto, int Quantita) {
            return base.Channel.Addquantitaprodotto(IDprodotto, Quantita);
        }
        
        public System.Threading.Tasks.Task<bool> AddquantitaprodottoAsync(string IDprodotto, int Quantita) {
            return base.Channel.AddquantitaprodottoAsync(IDprodotto, Quantita);
        }
        
        public bool Minusquantitaprodotto(string IDprodotto, int Quantita) {
            return base.Channel.Minusquantitaprodotto(IDprodotto, Quantita);
        }
        
        public System.Threading.Tasks.Task<bool> MinusquantitaprodottoAsync(string IDprodotto, int Quantita) {
            return base.Channel.MinusquantitaprodottoAsync(IDprodotto, Quantita);
        }
        
        public GestioneMagazzino.ServiceReference1.ProdottoClass Disprodotto(string Idprodotto) {
            return base.Channel.Disprodotto(Idprodotto);
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.ProdottoClass> DisprodottoAsync(string Idprodotto) {
            return base.Channel.DisprodottoAsync(Idprodotto);
        }
        
        public bool AlterNomeProdotto(string IDprodotto, string Nome) {
            return base.Channel.AlterNomeProdotto(IDprodotto, Nome);
        }
        
        public System.Threading.Tasks.Task<bool> AlterNomeProdottoAsync(string IDprodotto, string Nome) {
            return base.Channel.AlterNomeProdottoAsync(IDprodotto, Nome);
        }
        
        public bool AlterPrezzoProdotto(string IDprodotto, double Prezzo) {
            return base.Channel.AlterPrezzoProdotto(IDprodotto, Prezzo);
        }
        
        public System.Threading.Tasks.Task<bool> AlterPrezzoProdottoAsync(string IDprodotto, double Prezzo) {
            return base.Channel.AlterPrezzoProdottoAsync(IDprodotto, Prezzo);
        }
        
        public GestioneMagazzino.ServiceReference1.FatturaAcquistoClass[] FattureAcquistoList() {
            return base.Channel.FattureAcquistoList();
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.FatturaAcquistoClass[]> FattureAcquistoListAsync() {
            return base.Channel.FattureAcquistoListAsync();
        }
        
        public GestioneMagazzino.ServiceReference1.FatturaVenditaClass[] FattureVenditaList() {
            return base.Channel.FattureVenditaList();
        }
        
        public System.Threading.Tasks.Task<GestioneMagazzino.ServiceReference1.FatturaVenditaClass[]> FattureVenditaListAsync() {
            return base.Channel.FattureVenditaListAsync();
        }
        
        public bool AlterPagatoFattura(string Nfattura) {
            return base.Channel.AlterPagatoFattura(Nfattura);
        }
        
        public System.Threading.Tasks.Task<bool> AlterPagatoFatturaAsync(string Nfattura) {
            return base.Channel.AlterPagatoFatturaAsync(Nfattura);
        }
        
        public bool InsertFatturaVendita(string Nfattura, string CodUtente, string CodCliente, string CodProdotto, int Quantita, bool Pagamento) {
            return base.Channel.InsertFatturaVendita(Nfattura, CodUtente, CodCliente, CodProdotto, Quantita, Pagamento);
        }
        
        public System.Threading.Tasks.Task<bool> InsertFatturaVenditaAsync(string Nfattura, string CodUtente, string CodCliente, string CodProdotto, int Quantita, bool Pagamento) {
            return base.Channel.InsertFatturaVenditaAsync(Nfattura, CodUtente, CodCliente, CodProdotto, Quantita, Pagamento);
        }
        
        public bool InsertFatturaAcquisto(string Nfattura, string CodUtente, string CodFornitore, string CodProdotto, int Quantita, double PrezzoAcquisto) {
            return base.Channel.InsertFatturaAcquisto(Nfattura, CodUtente, CodFornitore, CodProdotto, Quantita, PrezzoAcquisto);
        }
        
        public System.Threading.Tasks.Task<bool> InsertFatturaAcquistoAsync(string Nfattura, string CodUtente, string CodFornitore, string CodProdotto, int Quantita, double PrezzoAcquisto) {
            return base.Channel.InsertFatturaAcquistoAsync(Nfattura, CodUtente, CodFornitore, CodProdotto, Quantita, PrezzoAcquisto);
        }
        
        public string NFatturaVendita() {
            return base.Channel.NFatturaVendita();
        }
        
        public System.Threading.Tasks.Task<string> NFatturaVenditaAsync() {
            return base.Channel.NFatturaVenditaAsync();
        }
    }
}
